[profile.default]

src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
tenderly = "https://virtual.sepolia.rpc.tenderly.co/60a1910e-d796-4bd9-97c6-4d3bf1aabda5"
